version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: banking-mysql
    environment:
      MYSQL_DATABASE: banking
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: