version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: banking-mysql
    environment:
      MYSQL_DATABASE: banking
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpass

volumes:
  mysql_data:
